//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSensor.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalSensor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1. Put a sensor into 1st Sample.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _1PGuide1 {
            get {
                return ResourceManager.GetString("1PGuide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. Adjust the 1st value using the arrows or keypad, and then apply to calibration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _1PGuide2 {
            get {
                return ResourceManager.GetString("1PGuide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. If you want to cancel calibration, Press [Stop] button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _1PGuide3 {
            get {
                return ResourceManager.GetString("1PGuide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1P Sample과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _1PSample {
            get {
                return ResourceManager.GetString("1PSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2P Buffer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _2PBuffer {
            get {
                return ResourceManager.GetString("2PBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Put a sensor into 1st Buffer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _2PGuide1 {
            get {
                return ResourceManager.GetString("2PGuide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. After the sensor stabilized, Press [Apply] button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _2PGuide2 {
            get {
                return ResourceManager.GetString("2PGuide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. If you want to cancel calibration, Press [Stop] button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _2PGuide3 {
            get {
                return ResourceManager.GetString("2PGuide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibration Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CalibrationStatus {
            get {
                return ResourceManager.GetString("CalibrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibration Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CalibrationValue {
            get {
                return ResourceManager.GetString("CalibrationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goodbye과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Farewell {
            get {
                return ResourceManager.GetString("Farewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorData {
            get {
                return ResourceManager.GetString("SensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data (mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorDataMv {
            get {
                return ResourceManager.GetString("SensorDataMv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorType {
            get {
                return ResourceManager.GetString("SensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zero Calibration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZeroCalibration {
            get {
                return ResourceManager.GetString("ZeroCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Put a sensor into DI water.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZeroGuide1 {
            get {
                return ResourceManager.GetString("ZeroGuide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. After the sensor stabilized, Press [Apply] button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZeroGuide2 {
            get {
                return ResourceManager.GetString("ZeroGuide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. If you want to cancel calibration, Press [Stop] button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZeroGuide3 {
            get {
                return ResourceManager.GetString("ZeroGuide3", resourceCulture);
            }
        }
    }
}
